countries = {
        'China': 0,
        'Italy': 1,
        'Spain': 2,
        'USA': 3,
        'Germany': 4,
        'Iran': 5,
        'France':6,
        'South Korea':7,
        'Switzerland' : 8,
        'UK':9,
        'Netherlands':10,
        'Austria':11,
        'Belgium':12,
        'Norway':13,
        'Sweden':14,
        'Canada':15,
        'Denmark':16,
        'Portugal':17,
        'Malaysia':18,
        'Brazil':19,
        'Australia':20,
        'Japan':21,
        'Czehia':22,
        'Turkey':23,
        'Israel':24,
        'Ireland':25,
        'Diamond-Princess':26,
        'Luxembourg':27,
        'Pakistan':28,
        'Chile':29,
        'poland':30,
        'Eurador':31,
        'Greece':32,
        'Finland':33,
        'Qatar':34,
        'Iceland':35,
        'Indonesia':36,
        'Singapore':37,
        'Thailand':38,
        'Saudi-Arabia':39,
        'Slovenia':40,
        'Romania':41,
        'India':42,
        'Peru':43,
        'Bahrain':44,
        'Philippines':45,
        'Russia':46,
        'Estonia':47,
        'Egypt':48,
        'Hong-Kong':49,
        'South-Africa':50,
        'Lebanon':51,
        'Iraq':52,
        'Croatia':53,
        'Mexico':54,
        'Panama':55,
        'Colombia':56,
        'Slovakia':57,
        'Kuwait':58,
        'Serbia':59,
        'Bulgaria':60,
        'San-Marino':61,
        'Armenia':62,
        'Argentina':63

    }
